project:
  type: website
  output-dir: docs

website:
  title: "Infectious disease surveillance"
  navbar:
    right:
      - about.qmd
  sidebar:
    logo: "img/booklogo.jpg"
    style: "floating"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: "Aims"
        href: why.qmd
        contents:
          - case_based_measures.qmd
          - community_based_measures.qmd
          - guiding_people.qmd
          - guiding_medicine.qmd
          - science.qmd
          - resources.qmd
      - section: "Origins"
        href: why.qmd
        contents:
          - decisions.qmd
          - aourndtheworld.qmd
          - goals.qmd
      - section: "Steps"
        href: steps.qmd
        contents:
          - step1.qmd
          - step2.qmd
          - step3.qmd
          - step4.qmd
          - step5.qmd
          - step6.qmd
          - step7.qmd
      - section: "Categories"
        href: categories.qmd
        contents:
          - category1.qmd
          - category2.qmd
          - category3.qmd
          - category4.qmd
          - category5.qmd
      - section: "Evaluation"
        href: why.qmd
        contents:
          - dataquality.qmd
          - evaluations.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



