project:
  type: book
  output-dir: docs

book:
  title: "Infectious disease surveillance"
  subtitle: "Learn how infectious diseases are monitored"
  author: "Jakob Schumacher"
  license: "CC BY"
  page-footer:
    right: "Version: 1.0.0 - September 2024"
  favicon: img/logo.png
  site-url: https://jakobschumacher.github.io/infectious-disease-surveillance/
  repo-url: https://github.com/jakobschumacher/infectious-disease-surveillance
  repo-actions: [edit, issue]
  page-navigation: true
  sidebar:
    collapse-level: 1
    logo: img/logo.png
  downloads:
    - pdf
    - epub
  chapters:
  - index.qmd
  - preface.qmd
  - presentations.qmd
  - part: Presentations
    chapters:
      - 1_Overview/01_overview_background.qmd
      - 1_Overview/03_overview_types.qmd
      - 1_Overview/05_overview_evaluation.qmd
  - part: BOOK
    chapters:
      - 2_Background/03_background_definition.qmd
      - 2_Background/04_background_othersurveillance.qmd
      - 2_Background/05_background_objectives.qmd
      - 2_Background/06_background_legal.qmd
      - text: "---"
      - 3_Steps/step1.qmd
      - 3_Steps/step2.qmd
      - 3_Steps/step3.qmd
      - 3_Steps/step4.qmd
      - 3_Steps/step5.qmd
      - 3_Steps/step6.qmd
      - 3_Steps/step7.qmd
      - text: "---"
      - 4_Types/02_type_case.qmd
      - 4_Types/03_type_syndromic.qmd
      - 4_Types/04_type_event.qmd
      - 4_Types/05_type_wastewater.qmd
      - 4_Types/06_type_mortality.qmd
      - 4_Types/07_type_massgathering.qmd
      - 4_Types/08_type_activevspassive.qmd
      - 4_Types/09_type_sentinel.qmd
  # - part: Attributes of surveillance
  #   chapters:
  #     - 5_Attributes/01_sensitvity.qmd
  #     - 5_Attributes/02_attributes_validity.qmd
  #     - 5_Attributes/03_attributes_timeliness.qmd
  #     - 5_Attributes/04_attributes_usefulness.qmd
  #     - 5_Attributes/05_attributes_representativeness.qmd
  #     - 5_Attributes/06_attributes_simplicity.qmd
  #     - 5_Attributes/07_attributes_flexibility.qmd
  #     - 5_Attributes/08_attributes_acceptability.qmd
  #     - 5_Attributes/09_attributes_otherattributes.qmd

format:
  html:
    theme: "styles.scss"
    toc: false
    lightbox: true
    modified-date: last-modified

  pdf:
    documentclass: scrreprt
  epub:
    cover-image: img/logo.png
