project:
  type: book
  output-dir: docs

book:
  title: "Infectious disease surveillance"
  subtitle: "Learn how infectious diseases are monitored"
  author: "Jakob Schumacher"
  license: "CC BY"
  page-footer:
    right: "Version: 0.5 - September 2023"
  favicon: img/logo.png
  site-url: https://jakobschumacher.github.io/infectious-disease-surveillance/
  repo-url: https://github.com/jakobschumacher/infectious-disease-surveillance
  repo-actions: [edit, issue]
  page-navigation: true
  sidebar:
    collapse-level: 2
    logo: img/logo.png
  downloads:
    - pdf
    - epub
  chapters:
  - index.qmd
  - text: Preface
    href: preface.qmd
  - presentations.qmd
  - part: Introduction
    chapters:
      - text: Definition
        href: 2_Introduction/03_background_definition.qmd
      - text: Domain
        href: 2_Introduction/04_background_othersurveillance.qmd
      - text: Int. Regulations
        href: 2_Introduction/06_background_legal.qmd
  - part: Stages
    chapters:
      - text: Objectives (1)
        href: 3_Stages/stage1.qmd
      - text: Event (2)
        href: 3_Stages/stage2.qmd
      - text: Collection (3)
        href: 3_Stages/stage3.qmd
      - text: Classification (4)
        href: 3_Stages/stage4.qmd
      - text: Data processing (5)
        href: 3_Stages/stage5.qmd
      - text: Analysis (6)
        href: 3_Stages/stage6.qmd
      - text: Communication (7)
        href: 3_Stages/stage7.qmd
      - text: Action (8)
        href: 3_Stages/stage8.qmd
  - part: Types
    chapters:
      - 4_Types/02_type_case.qmd
      - 4_Types/03_type_syndromic.qmd
      - 4_Types/04_type_event.qmd
      - 4_Types/05_type_wastewater.qmd
      - 4_Types/06_type_mortality.qmd
      - 4_Types/07_type_massgathering.qmd
      - 4_Types/08_type_activevspassive.qmd
      - 4_Types/09_type_sentinel.qmd
  # - part: Attributes of surveillance
  #   chapters:
  #     - 5_Attributes/01_sensitvity.qmd
  #     - 5_Attributes/02_attributes_validity.qmd
  #     - 5_Attributes/03_attributes_timeliness.qmd
  #     - 5_Attributes/04_attributes_usefulness.qmd
  #     - 5_Attributes/05_attributes_representativeness.qmd
  #     - 5_Attributes/06_attributes_simplicity.qmd
  #     - 5_Attributes/07_attributes_flexibility.qmd
  #     - 5_Attributes/08_attributes_acceptability.qmd
  #     - 5_Attributes/09_attributes_otherattributes.qmd
  - about.qmd


format:
  html:
    callout-appearance: simple
    lightbox: true
    modified-date: last-modified
    fig-width: 8
    fig-height: 6
    echo: false
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: img/logo.png


execute:
  echo: false
  warning: false
  message: false
  error: false
  freeze: auto
  cache: true
