---
title: "Surveillance around the world"
---


## Englisch
Nearly all complex biological and technical systems have mechanisms to monitor and control the system's condition. Many social systems also regularly analyze their current state. There are various terms for these status assessments: A scientific study is one form of status assessment, as is the police surveillance of a group or the evaluation of a project in the corporate sector. Surveillance is also a form of status assessment.

The term "surveillance" is derived from the French words "sur" and "veiller," meaning "to watch over" in English. This monitoring occurs in many forms. Tieman et al. distinguish three fundamental levels of surveillance: The first level is the Panopticon or top-down surveillance. This level is characterized by one actor (usually the state) monitoring a group of people, aiming to achieve a specific behavior among those being monitored. An example of such surveillance is the supervision of prisoners in a prison. The second level is rhizomatic surveillance, named after the rhizome, the network of fungi within the earth. In this level, data is collected covertly, as often happens on the internet. An example would be the surveillance conducted by Cambridge Analytica. The third level is participatory surveillance, characterized by active participation from citizens who conduct surveillance, for example, by sharing photos and information. This is vividly depicted in the book and film The Circle. Epidemiological surveillance is a component of the first level of surveillance.

Epidemiological surveillance (hereinafter referred to as "surveillance") is the continuous systematic collection, scientific analysis, and evaluation of health data, as well as the timely reporting of the evaluated results for the purpose of planning, implementing, and evaluating measures for disease prevention and control. Surveillance thus differs from similar concepts of status assessment. Surveillance is regular and usually permanent. This distinguishes it from an evaluation, which typically relates to a single event. Surveillance is well-defined, meaning it is usually clear from the outset what will be examined and how, and what results are expected. This contrasts with a scientific investigation, which aims to uncover the unknown. Surveillance is usually commissioned by an actor with a specific goal, distinguishing it from the purposeless collection of data that is analyzed out of interest.

Surveillance is firmly anchored in German and international legal systems. The International Health Regulations—one of the few nearly globally applicable frameworks—include articles that require surveillance from states. These articles aim to prevent cross-border threats from infectious diseases. During the COVID-19 pandemic, the value of such international collaboration became evident. There are currently efforts to supplement the International Health Regulations with an International Treaty on Pandemic Prevention. Surveillance is also a component of the “Essential Public Health Operations.” The goal of this fundamental component is to provide information and insights for health needs assessments, health impact assessments, and the planning of health services.

Surveillance has a purpose. This purpose is usually to take public health measures to avert or minimize a health threat. Therefore, the guiding principle of surveillance is "data for action." Sometimes it is also presented as "information for action" to emphasize that data must first be evaluated and thereby transformed into information. The guiding principle was originally formulated by Langumir as the following phrase: "Surveillance for Action."

## Deutsch
Nahezu alle komplexeren biologischen und technischen Systeme verfügen über Mechanis-men um den Zustand des Systems zu überwachen und zu steuern. Auch viele soziale Systeme analysieren regelmäßig ihren aktuellen Zustand. Für diese Statuserhebungen gibt es ver-schiedene Begriffe: Eine wissenschaftliche Studie ist eine Form der Statuserhebung, ebenso wie die polizeiliche Überwachung einer Gruppierung oder die Evaluation eines Projekts im Unternehmensbereich. Auch Surveillance ist eine Form der Statuserhebung. 
Der Begriff „Surveillance“ leitet sich aus den französischen Wörtern „sur“ und „veiller“ ab und bedeutet auf Deutsch „überwachen“. Diese Überwachung erfolgt in vielen Formen. Tieman et al. unterscheiden drei grundlegende Stufen von Surveillance: Die erste Stufe ist die Stufe des Panoptikums oder der Top-Down-Surveillance. Diese Stufe ist dadurch gekenn-zeichnet, dass ein Akteur (in der Regel der Staat) eine Gruppe von Personen überwacht. Es ist das Ziel ein bestimmtes Verhalten bei den Überwachten zu erreichen. Ein Beispiel für eine solche Surveillance ist ein Beaufsichtigung von Häftlingen in einem Gefängnis. Die zwei-te Stufe ist die rhizomatische Surveillance. Sie ist benannt nach dem Rhizom, also dem Ge-flecht von Pilzen innerhalb der Erde. In dieser Stufe werden Daten verdeckt gesammelt, wie es beispielsweise vielfach im Internet geschieht. Ein Beispiel wäre die Überwachung durch Cambridge Analytica. Die dritte Stufe ist eine partizipatorische Surveillance. Ein Kennzeichen davon ist eine aktive Beteiligung von Bürgerinnen und Bürger die zum Beispiel dem Teilen von Fotos und Informationen eine Überwachung durchführen. Im Buch und Film The Circle ist dieses anschaulich dargestellt [1]. Eine epidemiologische Surveillance ist ein Bestandteil der ersten Stufe der Surveillance.  
Als epidemiologische Surveillance (im folgenden verkürzte als Surveillance bezeichnet) ist die fortlaufende systematische Sammlung, wissenschaftliche Analyse und Bewertung von Gesundheitsdaten sowie die zeitnahe Berichterstattung der bewerteten Ergebnisse zum Zweck der Planung, Durchführung und Bewertung von Maßnahmen zur Krankheitsprävention und -bekämpfung [2].  Die Surveillance grenzt sich damit von ähnlich gelagerten Konzepten der Statuserhebung ab. Surveillance ist regelmäßig und zumeist dauerhaft angelegt. Damit unterscheidet sich sich von einer Evaluation, die sich üblicherweise auf ein einzelnes Ge-schehnis bezieht. Die Surveillance ist ausdefiniert, d.h. es steht im Regefall von Anfang an fest was wie genau angeschaut wird und im Regelfall weiß man welche Ergebnisse man er-wartet. Dies ist im Gegensatz zu einer wissenschaftlichen Untersuchung, die ja gerade da-rauf abzielt unbekanntes aufzudecken. Die Surveillance ist üblicherweise von einem Akteur mit einem Ziel beauftragt womit die Surveillance im Gegensatz zu einer anlasslosen Samm-lung von Daten, die interessehalber ausgewertet wird. 
Surveillance ist fest im deutschen und internationalen Rechtssystem verankert. Die Interna-tionalen Gesundheitsvorschriften – eines der wenigen nahezu weltweit gültigen Regelwerke – beinhalten Artikel, die von den Staaten eine Surveillance fordern. Diese Artikel zielen da-rauf ab, grenzüberschreitende Gefahren durch Infektionskrankheiten abzuwehren. Während der COVID-19-Pandemie hat sich der Wert einer solchen internationalen Zusammenarbeit deutlich gezeigt. Derzeit gibt es Bestrebungen, die Internationalen Gesundheitsvorschriften durch einen Internationalen Vertrag zur Pandemieprävention zu ergänzen [3]. Surveillance ist ebenfalls ein Baustein der “Essential public health operations”. Ziel dieses grundlegenden Bausteines ist es Informationen und Erkenntnisse für Gesundheitsbedarfsanalysen, Gesund-heitsfolgenabschätzungen und die Planung von Gesundheitsdiensten bereitzustellen. [4]
Eine Surveillance hat ein Ziel. Dieses Ziel ist im Regelfall Public Health Maßnahmen zu er-greifen um eine Gesundheitsgefahr abzuwenden oder zu minimieren. Daher ist auch der Leitspruch der Surveillance “Daten für Taten”. Manchmal wird er auch als “Informationen für Aktionen” dargestellt um zu betonen, dass es Daten erst bewertet werden müssen und damit in Information umgewandelt werden. Der Leitspruch ist seiner ursprünglichen Form von Langumir als folgende Formel dargestellt: “Surveillance for Action” 
