---
title: "Infectious disease surveillance"
author: "Jakob Schumacher"
---
##	Warum braucht es eine epidemiologische Surveillance
Am 28. Oktober 2020 trafen sich Angela Merkel und die Ministerpräsidentinnen und Minis-terpräsidenten, um Maßnahmen gegen die zweite Welle der COVID-19-Pandemie zu disku-tieren. Obwohl wir nicht genau wissen, welche Informationen auf ihren Sprechzetteln stan-den, können wir davon ausgehen, dass die Daten und Zahlen des Meldewesens nach dem Infektionsschutzgesetz eine zentrale Rolle spielten. In der anschließenden Konferenz wurden die Verdopplungszeit und die Zahl der belegten Intensivbetten als Begründung für einschnei-dende Maßnahmen herangezogen. Das Surveillance-System für Infektionskrankheiten spielt somit eine entscheidende Rolle für dasWohl der gesamten Nation.
##	Was ist Surveillance
Nahezu alle komplexeren biologischen und technischen Systeme verfügen über Mechanis-men um den Zustand des Systems zu überwachen und zu steuern. Auch viele soziale Systeme analysieren regelmäßig ihren aktuellen Zustand. Für diese Statuserhebungen gibt es ver-schiedene Begriffe: Eine wissenschaftliche Studie ist eine Form der Statuserhebung, ebenso wie die polizeiliche Überwachung einer Gruppierung oder die Evaluation eines Projekts im Unternehmensbereich. Auch Surveillance ist eine Form der Statuserhebung. 
Der Begriff „Surveillance“ leitet sich aus den französischen Wörtern „sur“ und „veiller“ ab und bedeutet auf Deutsch „überwachen“. Diese Überwachung erfolgt in vielen Formen. Tieman et al. unterscheiden drei grundlegende Stufen von Surveillance: Die erste Stufe ist die Stufe des Panoptikums oder der Top-Down-Surveillance. Diese Stufe ist dadurch gekenn-zeichnet, dass ein Akteur (in der Regel der Staat) eine Gruppe von Personen überwacht. Es ist das Ziel ein bestimmtes Verhalten bei den Überwachten zu erreichen. Ein Beispiel für eine solche Surveillance ist ein Beaufsichtigung von Häftlingen in einem Gefängnis. Die zwei-te Stufe ist die rhizomatische Surveillance. Sie ist benannt nach dem Rhizom, also dem Ge-flecht von Pilzen innerhalb der Erde. In dieser Stufe werden Daten verdeckt gesammelt, wie es beispielsweise vielfach im Internet geschieht. Ein Beispiel wäre die Überwachung durch Cambridge Analytica. Die dritte Stufe ist eine partizipatorische Surveillance. Ein Kennzeichen davon ist eine aktive Beteiligung von Bürgerinnen und Bürger die zum Beispiel dem Teilen von Fotos und Informationen eine Überwachung durchführen. Im Buch und Film The Circle ist dieses anschaulich dargestellt [1]. Eine epidemiologische Surveillance ist ein Bestandteil der ersten Stufe der Surveillance.  
Als epidemiologische Surveillance (im folgenden verkürzte als Surveillance bezeichnet) ist die fortlaufende systematische Sammlung, wissenschaftliche Analyse und Bewertung von Gesundheitsdaten sowie die zeitnahe Berichterstattung der bewerteten Ergebnisse zum Zweck der Planung, Durchführung und Bewertung von Maßnahmen zur Krankheitsprävention und -bekämpfung [2].  Die Surveillance grenzt sich damit von ähnlich gelagerten Konzepten der Statuserhebung ab. Surveillance ist regelmäßig und zumeist dauerhaft angelegt. Damit unterscheidet sich sich von einer Evaluation, die sich üblicherweise auf ein einzelnes Ge-schehnis bezieht. Die Surveillance ist ausdefiniert, d.h. es steht im Regefall von Anfang an fest was wie genau angeschaut wird und im Regelfall weiß man welche Ergebnisse man er-wartet. Dies ist im Gegensatz zu einer wissenschaftlichen Untersuchung, die ja gerade da-rauf abzielt unbekanntes aufzudecken. Die Surveillance ist üblicherweise von einem Akteur mit einem Ziel beauftragt womit die Surveillance im Gegensatz zu einer anlasslosen Samm-lung von Daten, die interessehalber ausgewertet wird. 
Surveillance ist fest im deutschen und internationalen Rechtssystem verankert. Die Interna-tionalen Gesundheitsvorschriften – eines der wenigen nahezu weltweit gültigen Regelwerke – beinhalten Artikel, die von den Staaten eine Surveillance fordern. Diese Artikel zielen da-rauf ab, grenzüberschreitende Gefahren durch Infektionskrankheiten abzuwehren. Während der COVID-19-Pandemie hat sich der Wert einer solchen internationalen Zusammenarbeit deutlich gezeigt. Derzeit gibt es Bestrebungen, die Internationalen Gesundheitsvorschriften durch einen Internationalen Vertrag zur Pandemieprävention zu ergänzen [3]. Surveillance ist ebenfalls ein Baustein der “Essential public health operations”. Ziel dieses grundlegenden Bausteines ist es Informationen und Erkenntnisse für Gesundheitsbedarfsanalysen, Gesund-heitsfolgenabschätzungen und die Planung von Gesundheitsdiensten bereitzustellen. [4]
Eine Surveillance hat ein Ziel. Dieses Ziel ist im Regelfall Public Health Maßnahmen zu er-greifen um eine Gesundheitsgefahr abzuwenden oder zu minimieren. Daher ist auch der Leitspruch der Surveillance “Daten für Taten”. Manchmal wird er auch als “Informationen für Aktionen” dargestellt um zu betonen, dass es Daten erst bewertet werden müssen und damit in Information umgewandelt werden. Der Leitspruch ist seiner ursprünglichen Form von Langumir als folgende Formel dargestellt: “Surveillance for Action” (Langmuir see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7149774/)
##	Die Schritte der Surveillance
Die Surveillance beobachtet im Regelfall Infektionsereignisse (Schritt 1). Diese Infektionser-eignisse werden erfasst (Schritt 2) und klassifiziert (Schritt 3). Anschließend werden die ent-standenen Daten verarbeitet (Schritt 4) und dann epidemiologisch bewertet (Schritt 5). Die entstandenen Informationen werden an Entscheidungsträger kommuniziert (Schritt 6). Die Maßnahme (Schritt 7) ist kein Teil der Surveillance im eigentlichen Sinne, aber die Sur-veillance ist darauf ausgerichtet. Die Unterteilung des Surveillance-Ablaufs kann in unter-schiedliche Schritte erfolgen, je nach dem gewünschten Detailgrad. Die Schritte können da-bei in einem komplexen System nacheinander abgearbeitet werden. Es ist aber auch mög-lich, diese Schritte gedanklich durch eine einzelne Person in wenigen Sekunden durchzuge-hen. Insgesamt sind die Schritte der Surveillance verwandt mit ähnlichen Konzepten wie dem Public Health Action Cycle, der die Notwendigkeit der Planung und Systematik des gesund-heitspolitischen Handelns verdeutlicht [5].
###	Schritt 1: Infektionsereignis
Die infektionsrelevanten Ereignisse, die in einem Surveillancesystem überwacht werden, können vielfältig sein. Die Wahl des jeweiligen Ereignisses hat dabei einen entscheidenden Einfluss auf das ganze System. Deshalb werden Surveillancesysteme häufig hiernach be-nannt: Die Notaufnahmesurveillance ist ein solches Beispiel. Auch die Unterteilung von Sur-veillancesystem erfolgt häufig anhand des Ereignisses, dass analysiert wird: so beruht die Einteilung eines Systems als “syndromic surveillance” darauf, dass Syndrome überwacht werden. Ein klassisches Ereigniss, das überwacht wird, ist das Auftreten einer Infektions-krankheiten bei einem Menschen. Es gibt aber viele Variationen und weitere Infektionser-eignisse, die eine Relevanz haben können: Ein freies Intensivbett, die Besiedelung eines Menschen mit einem Erreger, die ärztliches ICD-10 Einstufung eines Patienten oder einer Patientin, das Finden eines Zeitungsartikels zu einem Krankheitsgeschehen, die subjektive Bewertung eines ÖGD-Mitarbeiters, dass etwas eine Gefahr für die Bevölkerung darstellt.
###	Schritt 2: Erfassung
Die Infektionsereignisse werden erfasst. Wie genau die Erfassung erfolgt, hängt dabei vom jeweiligen Surveillancesystem ab. Dies passiert z.B. durch eine Meldung einer Ärztin oder eines Arztes. Ein Ereignis kann aber auch erfasst werden durch eine beauftragte Laborunter-suchung beispielsweise eine PCR-Untersuchung im Abwasser. Andere Erfassung erfolgen durch die Gesundheitsämter, die nach einer ersten Meldung weitere Fälle ermitteln. Es gibt auch eine Nutzung von anderen Datenquellen, die nicht primär für die Surveillance erhoben wurden, z.B. Krankheitsmeldungen an die Krankenkasse oder Todesbescheinigungen von Ärz-tinnen und Ärzten. Auch dieser Schritt gibt Anlass für die Bennung eines Surveillancesystems: Arzt-basiertes System im Gegensatz zu einem Labor-basiertes System oder aber auch Sekun-därdatensurveillance.
###Schritt 3: Klassifikation
Klassifikation bedeutet, dass die erfassten Ereignisse eingeteilt werden. Ein Mensch oder eine Software entscheidet anhand einer Definition auf welche Art und Weise das Ereignis als Datenpunkt mit aufgenommen wird. Häufig ist die Klassifikation eine Absprache was genau als Ereignis zählt ist und was nicht. Diese Klassifikation erfolgt häufig durch eine sogenannte Falldefinition. Eine Klassifizierung ist wichtig, denn erfasste Ereignisse können fehlerhaft sein und sollte nicht gezählt werden. Oder es liegen nicht genug Informationen vor, um zu ent-scheiden ob ein echtes Ereignis vorliegt oder nicht. Ohne eine Klassifikation bilden die Ereig-nisse eine unklare Sammlung mit zweifelhafter Bedeutung. Die Klassifikation ist häufig ein versteckter Teil des Surveillancesystem oder so im System eingebaut, dass er nicht als sol-cher erkannt wird. So ist die Anwendung der Falldefinitionen im Meldewesen in die Mel-desoftware eingebaut. Auch bei zunächst trivial erscheinenden Klassifizierungen müssen wichtige Definitionen vereinbart werden: Zählt bei der Mortalitätssurveillance der Tod eines Touristen mit ausländischem Pass als Todesfall im Sinne der Surveillance?
###	Schritt 4: Datenverarbeitung
Die Datenverarbeitung ist in der klassischen Surveillanceliteratur wenig erwähnt, stellt aber einen Schritt dar, der die Surveillancesysteme enscheidend verbessert. Viele Personen sind auf allen Ebenen mit der Datenverarbeitung in Surveillancesystemen beschäftigt. Wurde früher in Surveillancesystem monatlich per Brief übermittelt so erfolgt der Datenfluß heute zumeist über Schnittstellen zwischen Softwareprogrammen und Datenbanken. Die Art und Weise wie die Daten übermittelt werden, beeinflusst die Datenqualität und damit auch die Bewertung der Daten. Die Datenverarbeitung beinhaltet auch die Anwendung von Scripten, die die Datenmengen für die anschließende Bewertung vorbereitet. Eine automatisierte Ausbruchserkennung ist ein Beispiel dafür. Dabei werden die Daten mit Hilfe eines Algo-rithmus oder auch mittels machine-learning analysiert und es wird festgestellt ob eine hohe Wahrscheinlichkeit für ein Ausbruch vorliegt. Der entstehende Datensatz kann als Open Data bereitgestellt werden. Dieses ist ein Veröffentlichungsform, die in der letzten Zeit stark zu-genommen hat.
###	Schritt 5: Bewertung
Der Bewertungsschritt besteht aus der Analyse der Daten und dem anschließenden Ziehen von Schlüssen, mit anderen Worten die vorhandenen Daten werden in Informationen umge-wandelt. In manchen Fällen ist eine Bewertung einfach durchzuführen, zum Beispiel bei der Meldung eines Ebola-Falles bei einem Reiserückkehrer ist es klar, dass dieses ein wichtiges Ereignis darstellt, dass Maßnahmen nach sich zieht. In anderen Fällen ist eine Bewertung hochkomplex und erfordert viel Erfahrung und Austausch zwischen den bewertenden Perso-nen: Ist ein relativer Anstieg einer Variante von SARS-CoV-2 ein Anlass für Maßnahmen? Dieser Bewertungsschritt wandelt Daten in Informationen um und folgt damit den ersten zwei Teilen des “data–information–knowledge–wisdom Pyramide” [6]. Die Bewertung ist dabei ein subjektiver Vorgang, der kontextabhängig ist. Für die Bewertung ist vor allem die Kenntnisse über die Limitationen ein wichtiges Element. Ein Fallanstieg mag auf dem Papier ein eindeutiges Ereignis sein, kann aber zum Beispiel durch eine intensivierte Erfassung ver-ursacht sein und damit weniger relevant und sogar ein Zeichen der Entspannung, z.B. wenn bei einer umfassenden Diagnostik aller Mitarbeitenden in einem Krankenhaus weniger Fälle als erwartet gefunden werden. Die Veröffentlichung als Open Data bedeutet, dass die Be-wertung nicht nur durch direkt dafür vorgesehene Personen erfolgt, sondern Allen die Mög-lichkeit dazu gibt. Diese ermöglicht eine unabhängige Kontrolle dieses Schrittes der Sur-veillance, birgt aber die Gefahr einer Fehlinterpretation.
###	Schritt 6: Kommunikation
Die Kommunikation ist die Verbreitung der erhaltenen Informationen in Wort, Schrift und Bild. Kommunikation besteht aus den traditionellen Elementen wie Pressemitteilung und Pressekonferenzen oder der Erstellung von Berichten. Kommunikation ist aber inzwischen auch Social media und Fact-checking. Auch die Darstellung von Daten und Informationen in Dashboards zählt zur Kommunikation. Nicht zuletzt ist die graphische Darstellung von Infor-mationen zu Zeit, Ort und Person ein Teil dieses Surveillance-Schritts. Die Kommunikation von epidemiologischen Informationen stand zum Ende der Pandemie stark im Fokus und ist ein Bereich mit einem starken Entwicklungspotential. Nahezu weltweit gab es einen relevan-ten Anteil der Bevölkerung, die die Maßnahmen zur Bekämpfung der COVID-19 Pandemie abgelehnt haben und dadurch einen Einfluss auf den Verlauf der Pandemie hatten.
###	Schritt 7: Public Health Maßnahmen
Maßnahmen sind streng genommen kein Schritt der Surveillance, aber sie sind das Ziel auf das die Surveillance hinarbeitet. Public Health Maßnahmen sind alle absichtlichen Anstren-gungen von beauftragten Akteuren, die auf die Verhinderung der Weiterverbreitung und generell auf die Minimierung von Schaden durch Infektionskrankheiten gerichtet sind. Maß-nahmen sind häufig gesetzlich beschrieben zum Beispiel im Infektionsschutzgesetz. Maß-nahmen lassen sich in fallbezogene Maßnahmen und bevölkerungsbezogene Maßnahmen unterteilen. Fallbezogene Maßnahmen beinhalten zum Beispiel die Aufklärung einer be-troffenen Person über Übertragungswege oder auch Maßnahmen wie Quarantäne. Bevölke-rungsbezogene Maßnahmen sind Maßnahmen, die auf viele Menschen z.B. die Bevölkerung eines Bundeslandes einwirken. 
##	Kategorisierung von Surveillancesystemen
Surveillancesysteme können in unterschiedliche Kategorien eingeteilt werden um bestimmte Charakteristika hervorzuheben. Dabei sind die Kategorien nicht ausschließend und ein Sur-veillancesystem kann zumeist in mehrere Kategorien einsortiert werden. 
###	Sentinel Surveillance
Eine Sentinel Surveillance ist ein System, dass nicht alle Personen überwacht über die eine Aussage getroffen werden soll, sondern nur ein definierter Anteil. Daher auch der Name von „Sentinel“, was Wächter bedeutet. Durch ein Sentinalsystem werden Kosten gespart und es können im Regelfall detailliertere Informationen erhoben werden. Für die Beurteilung von epidemiologischen Fragestellungen ist es häufig der Detailgrad von entscheidender Bedeu-tung, zum Beispiel um den Schweregrad einer Erkrankung zu beurteilen. Beispielsweise kön-nen für die Erhebung von respiratorischen Erkrankungen einige Arztpraxen ausgesucht wer-den, die detaillierte Informationen liefern inklusive Impfstatus, Schweregrad und auch In-formationen über Personen ohne respiratorische Erkrankungen als Vergleichsgruppe. Von diesen Arztpraxen kann dann auf alle Arztpraxen geschlossen werden. Die Alternative direkt alle Arztpraxen zu untersuchen, ist sehr viel aufwändiger und birgt die Gefahr, dass die Da-tenqualität sinkt, weil viele Informationen nur unweillig bereitgestellt werden. 
### Ereignis-basierte Surveillance 
Die Ereignis-basierte Surveillance ist besser bekannt unter dem englichen Namen event-based surveillance. Sie fällt etwas aus dem üblichen Konzept einer Surveillance heraus, denn die überwachten Ereignisse sind im Vorfeld nicht bekannt. Durch ein definiertes System wird nach relevanten Ereignissen gesucht. Ein Beispiel für eine solche Surveillance ist eine Exper-tenkommission die bei regelmäßigen Treffen Ereignisse sammelt, die von Relevanz sein könnten. Solche Ereignisse können Zeitungsmeldungen sein oder Gerüchte, die die Experten zu Ohren gekommen sind. Die gesammelten Ereignisse werden bewertet und die entschei-denden Informationen daraus werden weitergegeben.  
###	Syndromische Surveillance
Als Syndromische Surveillance werden solche Surveillancesysteme bezeichnet welche als relevantes Ereignis keine diagnostizierte Krankheit haben, sondern Fälle aus einer Gruppe von Krankheiten erfasst werden. Zum Beispiel wird in einer syndromischen Surveillance statt einer SARS-CoV-2 Infektion nur ein Fall einer akuten respiratorischen Erkrankung erfasst. Durch ein solches Vorgehen wird die Surveillance sensitiver und erfasst ein breiteres Spekt-rum von Krankheiten. Bei einem Signal, dass auf ein relevantes Ereignis z.B. ein Ausbruch hindeutet, kann dann genauer untersucht werden um den exakten Erreger zu identifizieren.
### Aktive und passive Surveillance
Ein aktives Surveillancesystem bedeutet, dass es eine Gruppe von Personen gibt, die aktiv für das Surveillancesystem Informationen erhebt. Ein passives Surveillancesystem verwendet dagegen Daten, die für einen anderen Zweck erhoben werden. Ein passives Surveillancesys-tem wird manchmal auch Sekundärdatenalayse genannt. Beispielsweise könnten in Mitar-beitende einer Organisation von Haus zu Haus gehen um Informationen zu erhalten – dieses wäre ein aktives Surveillancesystem oder es könnten Daten aus einer Datenbank eines Kran-kenhauses verwendet werden – dieses wäre ein passives Surveillancesystem.  
###	Mass-Gathering Surveillance
Die Mass-Gathering Surveillance bezeichnet eine Surveillance, die für den Zeitraum eines besonderen Ereignisses aufgesetzt wird. Dabei werden im Regelfall unterschiedliche Kom-ponenten von anderen Surveillancesystmen eingesetzt. Beispielsweise kann während einer Europameisterschaft im Fußball eine gesonderte Surveillance eingeführt werden. 
##	Das Meldewesen
Das deutsche infektionsepidemiologische Meldewesen nach dem Infektionsschutzgesetz ist das Rückgrat der infektiologischen Surveillance in Deutschland. Es hat sich historisch entwi-ckelt und ist auch schon im Reichsseuchengesetz von 1900 vorhanden. Dort heißt es zum Beispiel: “Jede Erkrankung und jeder Todesfall an Ausatz (Lepra), Cholera (asiatischer), Fleckfieber (Flecktyphus), Gelbfieber, Pest (orientalischer Beulenpest), Pocken (Blattern) […] ist […] der zuständigen Polizeibehörde unverzüglich anzuzeigen.” (https://www.reichstagsprotokolle.de/Blatt_k10_bsb00002789_00558.html) Das bestehende Meldewesen wurde im Jahr 2000 mit der Gestaltung des Infektionsschutzgesetzes erarbeitet. Dort ist in den §§ 6 bis 11 das Meldewesen gesetzlich geregelt. Die entsprechenden Para-graphen wurden vielfach geändert zumeist als Reaktion auf ein akutes Geschehen wie z.B. der HUS-Epidemie 2011. 
Das Ereignisse (Schritt 1) die überwacht werden, sind im Regelfall das Auftreten von Infekti-onskrankheiten. Das Meldewesen umfasst aber diverse Meldepflichten und mehrere Mel-dewege. Damit kann es als eine Sammlung von verwandten aber eigentlich unterschiedli-chen Surveillancesystemen betrachtet werden. Ein relevanter Bestandteil des Meldewesens ist die Meldepflicht für Ärztinnen und Ärzte sowie Pathologinnen und Pathologen und von weiteren Professionen. Das Ereignis das dadurch erfasst wird ist der Verdacht einer Erkran-kung, die Erkrankung sowie der Tod von einer definierten Anzahl von Infektionskrankheiten, die ärztlich diagnostiziert werden können. Dies betrifft zum Beispiel Masern, Polio, HUS. Ein weiterer relevanter Bestandteil des Meldewesens ist der Bereich der Meldepflicht für Labo-re. Das überwachte Ereignis ist ein Labornachweis, der auf eine akute Infektion hinweist. Diese Labormeldepflicht gilt für eine umfangreiche Anzahl von Infektionskrankheiten. Neben der Arztmeldepflicht und Labormeldepflicht existieren noch weitere Bestandteile z.B. eine nicht-namentliche Meldepflicht für den Labornachweis von bestimmte Infektionserreger wie HIV mit einem gesonderten Meldeweg.
Die Erfassung der Arzt- und Labormeldepflicht (Schritt 2) erfolgt im Regelfall durch die Mel-dung und durch die Ermittlung der Gesundheitsämter. Lange Jahre war die Art und Weise einer Meldung nicht festgelegt und erfolgte im Regelfall per Fax. Im letzten Jahrzehnt ist das Deutsche Elektronische Melde- und Informationssystem (DEMIS) entstanden. Dieses beinhal-tet primär eine Digitalisierung des Meldevorgangs vom Meldenden an das Gesundheitsamt. Diese Art der Meldung ist nun durch das IfSG für viele Meldewege gesetzlich vorgeschrie-ben. Die Art und Weise der Ermittlung der Gesundheitsämter ist nicht vorgeschrieben, wobei natürlich Einschränkungen durch die Persönlichkeitsrechte gelten (https://www.gesetze-im-internet.de/ifsg/__25.html). Eine übliche Ermittlung beinhaltet einen Anruf vom Gesund-heitsamt und ein Infektionsschutzinterview mit der betroffenen Personen. Das Meldewesen ist damit ein Mischsystem aus passiver und aktiver Surveillance. Passiv ist das System des-halb, weil die überwachten Ereignisse nicht aufgrund des Meldewesen existieren. Zum Bei-spiel wird in den allermeisten Fällen ein Labortest aus klinischen Gründen durchgeführt und nicht aus epidemiologischen Gründen. Aktiv ist das Surveillancesystem deshalb, weil die Ge-sundheitsämter aktiv ermitteln und die betroffenen Personen anrufen. Die Ermittlung ist ein zentraler Bestandteil des Berufsbildes der Hygieneinspektoren und Hygieneinspektorinnen.
Die Klassifizierung (Schritt 3) erfolgt im Meldewesen durch das Gesundheitsamt assistiert von der jeweiligen Meldesoftware. Nach Eingabe der ermittelten Daten gibt die Meldesoft-ware aus ob das Ereignis der festgelegten Definition entspricht. Dabei sind die Definitionen zweistufig. Zum einen ist festgelegt, welche Ereignisse an die Landesstelle und das RKI übermittelt werden “Übermittlungsdefinition” und zum anderen ist festgelegt welche Fälle offiziell in der Statistik des RKIs gezählt werden „Referenzdefinition“. Die Festlegung durch die Definition ist wichtig um eine Vergleichbarkeit herzustellen und damit einen Anstieg o-der Abfall der Anzahl von Fällen zu identifizieren. Zu Beginn der COVID-19-Pandemie änder-te die chinesische Regierung die Falldefinition von COVID-19 was zu einem artifiziellen sprunghaften Anstieg in der Statistik führte. Falldefinitionen können sensitiv sein in dem Sin-ne, dass sie möglichst viele Fälle erfassen oder sie können spezifisch sein, so dass sie nur eine geringe Anzahl von falsch-erkannten Fällen beinhalten. Falldefinitionen existieren nicht nur für eine Surveillancesystem sondern werden häufig auch gesondert für Ausbrüche fest-gelegt. Falldefinitionen sind darüber hinaus nicht unbedingt der Maßstab für die Durchfüh-rung von Maßnahmen. Bei einem Verdachtsfall eines hämorrhagischen Fiebers zum Beispiel muss nicht gewartet werden, dass eine Falldefinition erfüllt wird um Maßnahmen zu ergrei-fen.
Das Datenmanagement (Schritt 4) erfolgt nach der Klassifizierung. Das Meldewesen hat stark von einem professionelleren Datenmanagement profitiert. Vor Einführung der elektro-nischen Meldesoftware wurden die Daten umständlich und fehleranfällig per Brief oder Fax übermittelt, durch die zunehmende Digitalisierung und dem Abbau von Medienbrüchen wird das Datenmanagement zunehmend präziser und schneller. Die bekannteste Meldesoftware SurvNet vom Rober Koch-Institut setzt die Standards für die Übermittlung vom Gesundheits-amt an die Landesstelle und von dort an das Robert Koch-Institut. Das Datenmanagement erfolgt in Datenbanken, die am Robert Koch-Insitut betrieben werden. Im Datenmangement erfolgt die Qualitätssicherung und die Aufbereitung der Daten für den nachfolgenden Schritt der Bewertung. Die Aufbereitung beinhaltet dabei auch eine automatisierte Signalerken-nung, die mögliche Ausbrüche detektiert und passend darstellt. (DOI: 10.2807/1560-7917.ES.2016.21.13.30180)  
Die Bewertung (Schritt 5) der Daten des Meldewesens erfolgt auf allen drei Ebenen, der Kommune, dem Land und dem Bund.  
##	Fazit
Die Surveillance ist ein zentraler Bestandteil der Evidenzgewinnung in Deutschland.
