---
subtitle: Generel presentations about infectious disease surveillance 
---

# Presentations {.unnumbered}


## Einführung 
|Target|Description|
|---|---|
|[Presentation](1_Presentations/presentation_einfuehrung.html)|The link to the presentation|
|Content|This presentation gives an introduction to surveillance system. How it is defined, how it falls in the domain of general surveillance, what its objectives are |
|Time|90 Minutes|
|Language|German|
|Intended audience|Ärztinnen und Ärzte in Weiterbildung zum Facharzt für öffentliches Gesundheitswesen.| 
|Learning objectives|(1) Surveillance ist wichtiger denn je (2) "Daten für Taten" (3) Schritte der Surveillance (4) Surveillance muss durchdefiniert werden|


## Introduction to surveillance systems
|Target|Description|
|---|---|
|[Presentation](1_Presentations/presentation_introduction.html)|The link to the presentation|
|Content|This presentation gives an introduction to surveillance system. How it is defined, how it falls in the domain of general surveillance, what its objectives are |
|Time|15 Minutes|
|Language|English|
|Intended audience|Young professionals, Fellows of the European programme for intervention epidemiology| 
|Learning objectives|(1) Know the important parts of the definition (2) Understand the domain surveillance (3) Know the objectives|


## Stages of surveillance systems
|Target|Description|
|---|---|
|[Presentation](1_Presentations/presentation_stages.html)|The link to the presentation|
|Content|This presentation gives an overview of the stages of an surveillance system. |
|Time|10 Minutes|
|Language|English|
|Intended audience|Young professionals, Fellows of the European programme for intervention epidemiology| 
|Learning objectives| (1) Understand that the definition of surveillance includes most stages (2) The stages are: Events, Collection, Classification, Data management, Analysis, Communication, Action|

## Types of surveillance systems
|Target|Description|
|---|---|
|[Presentation](1_Presentations/presentation_types.html)|The link to the presentation|
|Content|This presentation gives an overview of the types of surveillance system e.g. case based, syndromic, event based, wastewater, active vs passive |
|Time|20 Minutes|
|Language|English|
|Intended audience|Young professionals, Fellows of the European programme for intervention epidemiology| 
|Learning objectives| (1) Understand that different overlapping types of surveillance system exist (2) Know what case based surveillance is (3) Know what syndromic surveillance is (4) Know what event based surveillance is |

 
## Attributes of surveillance systems  
|Target|Description|
|---|---|
|[Presentation](1_Presentations/presentation_attributes.html)|The link to the presentation|
|Content|This presentation covers the attributes of a surveillance system. It covers underestimation, validty, timeliness and other attributes |
|Time|20 Minutes|
|Language|English|
|Intended audience|Young professionals, Fellows of the European programme for intervention epidemiology| 
|Learning objectives| (1) Be able to describe characteristics of a surveillance system (2) Understand underestimation (3) Understand validity (4) Understand timeliness (5) Know that there are many attributes often with unclear defintions|


## Evaluation of surveillance systems
|Target|Description|
|---|---|
|[Presentation](1_Presentations/presentation_evaluation.html)|The link to the presentation|
|Content|This presentation gives an overview of how to evaluate a surveillance system. |
|Time|10 Minutes|
|Language|English|
|Intended audience|Young professionals, Fellows of the European programme for intervention epidemiology| 
|Learning objectives| (1) Learn the steps of an evaluation (2) need to adapt the evaluation to the trigger and the attributes (3) Surveillance is a team effort|


