---
title: "Step 1: Infection Event"
---

The infection-related events monitored in a surveillance system can be diverse. The choice of the specific event has a decisive impact on the entire system. Therefore, surveillance systems are often named after this event: Emergency room surveillance is one such example. The categorization of surveillance systems is also often based on the event being analyzed: For example, a system classified as “syndromic surveillance” is based on the monitoring of syndromes. A classic event that is monitored is the occurrence of an infectious disease in a person. However, there are many variations and other infection events that may be relevant: an available ICU bed, the colonization of a person by a pathogen, a physician's ICD-10 classification of a patient, the discovery of a newspaper article about a disease outbreak, or the subjective assessment of a public health department employee that something poses a threat to the population.



## Alterantive Events

Events are something that wants to be monitored. In infectious disease surveillance it is typically an infection. But i can also be other events as well: lab confirmation of a pathogen, free intensiv care beds, hospiatalisation because of a disease, vaccinations, death of person, a contact between to persons. One important but sometimes difficult distinction is differing between infection and disease. A lab confirmation usually shows an infection, which means that we know, that a person has a infection but is not necessarily sick, whereas a confirmation by a physician usually means that a person is sick. 

What event is monitored depends on the aim of the surveillance system. It is useful to be precise about the event that wants to be monitored. This helps in the communication and in the quality assessment. 
