---
title: "Steps of a surveillancesystem"
---

## Englisch

Surveillance typically monitors infection events (Step 1). These infection events are recorded (Step 2) and classified (Step 3). The resulting data is then processed (Step 4) and subsequently evaluated epidemiologically (Step 5). The generated information is communicated to decision-makers (Step 6). The measures taken (Step 7) are not part of surveillance in the strict sense, but surveillance is directed towards them. The breakdown of the surveillance process can be divided into different steps depending on the desired level of detail. These steps can be processed sequentially in a complex system. However, it is also possible for these steps to be mentally reviewed by a single person within a few seconds. Overall, the steps of surveillance are related to similar concepts, such as the Public Health Action Cycle, which emphasizes the need for planning and systematic public health actions.

3.1 Step 1: Infection Event

The infection-related events monitored in a surveillance system can be diverse. The choice of the specific event has a decisive impact on the entire system. Therefore, surveillance systems are often named after this event: Emergency room surveillance is one such example. The categorization of surveillance systems is also often based on the event being analyzed: For example, a system classified as “syndromic surveillance” is based on the monitoring of syndromes. A classic event that is monitored is the occurrence of an infectious disease in a person. However, there are many variations and other infection events that may be relevant: an available ICU bed, the colonization of a person by a pathogen, a physician's ICD-10 classification of a patient, the discovery of a newspaper article about a disease outbreak, or the subjective assessment of a public health department employee that something poses a threat to the population.
3.2 Step 2: Recording

Infection events are recorded. How exactly this recording takes place depends on the specific surveillance system. This may happen, for example, through a report from a doctor. An event can also be recorded through a commissioned laboratory examination, such as a PCR test in wastewater. Other recordings are made by health authorities, which investigate further cases after an initial report. There is also the use of other data sources not primarily collected for surveillance, such as illness reports to health insurance companies or death certificates from doctors. This step also often leads to the naming of a surveillance system: a physician-based system as opposed to a laboratory-based system, or secondary data surveillance.
3.3 Step 3: Classification

Classification means categorizing the recorded events. A person or software decides based on a definition how the event is included as a data point. Often, classification involves agreeing on what exactly counts as an event and what does not. This classification is often done using a so-called case definition. Classification is important because recorded events can be erroneous and should not be counted. Or there may not be enough information to decide whether a real event has occurred. Without classification, the events form an unclear collection with questionable significance. Classification is often a hidden part of the surveillance system or built into the system in a way that it is not recognized as such. For example, the application of case definitions in the reporting system is built into the reporting software. Even in seemingly trivial classifications, important definitions must be agreed upon: Does the death of a tourist with a foreign passport count as a death in the context of mortality surveillance?
3.4 Step 4: Data Processing

Data processing is seldom mentioned in classical surveillance literature, but it is a step that significantly improves surveillance systems. Many people at all levels are involved in data processing within surveillance systems. In the past, data was transmitted monthly by mail in surveillance systems, whereas today, data flow mostly occurs through interfaces between software programs and databases. The way data is transmitted affects data quality and, consequently, the evaluation of the data. Data processing also includes the application of scripts that prepare the data for subsequent evaluation. An example is automated outbreak detection. Here, data is analyzed using an algorithm or machine learning to determine whether there is a high probability of an outbreak. The resulting dataset can be made available as open data, a publication format that has increased significantly in recent times.
3.5 Step 5: Evaluation

The evaluation step consists of analyzing the data and subsequently drawing conclusions—in other words, converting the available data into information. In some cases, evaluation is straightforward; for example, when a case of Ebola is reported in a returning traveler, it is clear that this is an important event that necessitates action. In other cases, evaluation is highly complex and requires a lot of experience and exchange between the evaluators: Is a relative increase in a variant of SARS-CoV-2 a reason for action? This evaluation step converts data into information, following the first two parts of the "data–information–knowledge–wisdom" pyramid. Evaluation is a subjective process and context-dependent. Knowledge of the limitations is particularly important for evaluation. An increase in cases may seem like a clear event on paper but could be caused by intensified recording, making it less relevant and even a sign of relief, for example, if a comprehensive diagnostic of all hospital staff finds fewer cases than expected. The publication as open data means that the evaluation is not only carried out by designated individuals but is open to everyone, enabling independent verification of this step in surveillance but also posing the risk of misinterpretation.
3.6 Step 6: Communication

Communication is the dissemination of the obtained information in words, writing, and images. Communication consists of traditional elements such as press releases and press conferences or the preparation of reports. Communication now also includes social media and fact-checking. The presentation of data and information in dashboards also counts as communication. Last but not least, the graphical representation of information related to time, place, and person is part of this surveillance step. The communication of epidemiological information was a major focus towards the end of the pandemic and is an area with strong development potential. Almost worldwide, a significant portion of the population rejected the measures to combat the COVID-19 pandemic, thereby influencing the course of the pandemic.
3.7 Step 7: Public Health Measures

Measures are not strictly speaking a step of surveillance, but they are the goal towards which surveillance is directed. Public health measures are all deliberate efforts by commissioned actors aimed at preventing the further spread and generally minimizing the harm caused by infectious diseases. Measures are often legally defined, for example, in the Infection Protection Act. Measures can be divided into case-based measures and population-based measures. Case-based measures include, for example, informing an affected person about transmission routes or measures such as quarantine. Population-based measures are those that affect many people, for example, the population of a federal state.


## Deutsch
Die Surveillance beobachtet im Regelfall Infektionsereignisse (Schritt 1). Diese Infektionser-eignisse werden erfasst (Schritt 2) und klassifiziert (Schritt 3). Anschließend werden die ent-standenen Daten verarbeitet (Schritt 4) und dann epidemiologisch bewertet (Schritt 5). Die entstandenen Informationen werden an Entscheidungsträger kommuniziert (Schritt 6). Die Maßnahme (Schritt 7) ist kein Teil der Surveillance im eigentlichen Sinne, aber die Sur-veillance ist darauf ausgerichtet. Die Unterteilung des Surveillance-Ablaufs kann in unter-schiedliche Schritte erfolgen, je nach dem gewünschten Detailgrad. Die Schritte können da-bei in einem komplexen System nacheinander abgearbeitet werden. Es ist aber auch mög-lich, diese Schritte gedanklich durch eine einzelne Person in wenigen Sekunden durchzuge-hen. Insgesamt sind die Schritte der Surveillance verwandt mit ähnlichen Konzepten wie dem Public Health Action Cycle, der die Notwendigkeit der Planung und Systematik des gesund-heitspolitischen Handelns verdeutlicht [5].
3.1	Schritt 1: Infektionsereignis
Die infektionsrelevanten Ereignisse, die in einem Surveillancesystem überwacht werden, können vielfältig sein. Die Wahl des jeweiligen Ereignisses hat dabei einen entscheidenden Einfluss auf das ganze System. Deshalb werden Surveillancesysteme häufig hiernach be-nannt: Die Notaufnahmesurveillance ist ein solches Beispiel. Auch die Unterteilung von Sur-veillancesystem erfolgt häufig anhand des Ereignisses, dass analysiert wird: so beruht die Einteilung eines Systems als “syndromic surveillance” darauf, dass Syndrome überwacht werden. Ein klassisches Ereigniss, das überwacht wird, ist das Auftreten einer Infektions-krankheiten bei einem Menschen. Es gibt aber viele Variationen und weitere Infektionser-eignisse, die eine Relevanz haben können: Ein freies Intensivbett, die Besiedelung eines Menschen mit einem Erreger, die ärztliches ICD-10 Einstufung eines Patienten oder einer Patientin, das Finden eines Zeitungsartikels zu einem Krankheitsgeschehen, die subjektive Bewertung eines ÖGD-Mitarbeiters, dass etwas eine Gefahr für die Bevölkerung darstellt.
3.2	Schritt 2: Erfassung
Die Infektionsereignisse werden erfasst. Wie genau die Erfassung erfolgt, hängt dabei vom jeweiligen Surveillancesystem ab. Dies passiert z.B. durch eine Meldung einer Ärztin oder eines Arztes. Ein Ereignis kann aber auch erfasst werden durch eine beauftragte Laborunter-suchung beispielsweise eine PCR-Untersuchung im Abwasser. Andere Erfassung erfolgen durch die Gesundheitsämter, die nach einer ersten Meldung weitere Fälle ermitteln. Es gibt auch eine Nutzung von anderen Datenquellen, die nicht primär für die Surveillance erhoben wurden, z.B. Krankheitsmeldungen an die Krankenkasse oder Todesbescheinigungen von Ärz-tinnen und Ärzten. Auch dieser Schritt gibt Anlass für die Bennung eines Surveillancesystems: Arzt-basiertes System im Gegensatz zu einem Labor-basiertes System oder aber auch Sekun-därdatensurveillance.
3.3	Schritt 3: Klassifikation
Klassifikation bedeutet, dass die erfassten Ereignisse eingeteilt werden. Ein Mensch oder eine Software entscheidet anhand einer Definition auf welche Art und Weise das Ereignis als Datenpunkt mit aufgenommen wird. Häufig ist die Klassifikation eine Absprache was genau als Ereignis zählt ist und was nicht. Diese Klassifikation erfolgt häufig durch eine sogenannte Falldefinition. Eine Klassifizierung ist wichtig, denn erfasste Ereignisse können fehlerhaft sein und sollte nicht gezählt werden. Oder es liegen nicht genug Informationen vor, um zu ent-scheiden ob ein echtes Ereignis vorliegt oder nicht. Ohne eine Klassifikation bilden die Ereig-nisse eine unklare Sammlung mit zweifelhafter Bedeutung. Die Klassifikation ist häufig ein versteckter Teil des Surveillancesystem oder so im System eingebaut, dass er nicht als sol-cher erkannt wird. So ist die Anwendung der Falldefinitionen im Meldewesen in die Mel-desoftware eingebaut. Auch bei zunächst trivial erscheinenden Klassifizierungen müssen wichtige Definitionen vereinbart werden: Zählt bei der Mortalitätssurveillance der Tod eines Touristen mit ausländischem Pass als Todesfall im Sinne der Surveillance?
3.4	Schritt 4: Datenverarbeitung
Die Datenverarbeitung ist in der klassischen Surveillanceliteratur wenig erwähnt, stellt aber einen Schritt dar, der die Surveillancesysteme enscheidend verbessert. Viele Personen sind auf allen Ebenen mit der Datenverarbeitung in Surveillancesystemen beschäftigt. Wurde früher in Surveillancesystem monatlich per Brief übermittelt so erfolgt der Datenfluß heute zumeist über Schnittstellen zwischen Softwareprogrammen und Datenbanken. Die Art und Weise wie die Daten übermittelt werden, beeinflusst die Datenqualität und damit auch die Bewertung der Daten. Die Datenverarbeitung beinhaltet auch die Anwendung von Scripten, die die Datenmengen für die anschließende Bewertung vorbereitet. Eine automatisierte Ausbruchserkennung ist ein Beispiel dafür. Dabei werden die Daten mit Hilfe eines Algo-rithmus oder auch mittels machine-learning analysiert und es wird festgestellt ob eine hohe Wahrscheinlichkeit für ein Ausbruch vorliegt. Der entstehende Datensatz kann als Open Data bereitgestellt werden. Dieses ist ein Veröffentlichungsform, die in der letzten Zeit stark zu-genommen hat.
3.5	Schritt 5: Bewertung
Der Bewertungsschritt besteht aus der Analyse der Daten und dem anschließenden Ziehen von Schlüssen, mit anderen Worten die vorhandenen Daten werden in Informationen umge-wandelt. In manchen Fällen ist eine Bewertung einfach durchzuführen, zum Beispiel bei der Meldung eines Ebola-Falles bei einem Reiserückkehrer ist es klar, dass dieses ein wichtiges Ereignis darstellt, dass Maßnahmen nach sich zieht. In anderen Fällen ist eine Bewertung hochkomplex und erfordert viel Erfahrung und Austausch zwischen den bewertenden Perso-nen: Ist ein relativer Anstieg einer Variante von SARS-CoV-2 ein Anlass für Maßnahmen? Dieser Bewertungsschritt wandelt Daten in Informationen um und folgt damit den ersten zwei Teilen des “data–information–knowledge–wisdom Pyramide” [6]. Die Bewertung ist dabei ein subjektiver Vorgang, der kontextabhängig ist. Für die Bewertung ist vor allem die Kenntnisse über die Limitationen ein wichtiges Element. Ein Fallanstieg mag auf dem Papier ein eindeutiges Ereignis sein, kann aber zum Beispiel durch eine intensivierte Erfassung ver-ursacht sein und damit weniger relevant und sogar ein Zeichen der Entspannung, z.B. wenn bei einer umfassenden Diagnostik aller Mitarbeitenden in einem Krankenhaus weniger Fälle als erwartet gefunden werden. Die Veröffentlichung als Open Data bedeutet, dass die Be-wertung nicht nur durch direkt dafür vorgesehene Personen erfolgt, sondern Allen die Mög-lichkeit dazu gibt. Diese ermöglicht eine unabhängige Kontrolle dieses Schrittes der Sur-veillance, birgt aber die Gefahr einer Fehlinterpretation.
3.6	Schritt 6: Kommunikation
Die Kommunikation ist die Verbreitung der erhaltenen Informationen in Wort, Schrift und Bild. Kommunikation besteht aus den traditionellen Elementen wie Pressemitteilung und Pressekonferenzen oder der Erstellung von Berichten. Kommunikation ist aber inzwischen auch Social media und Fact-checking. Auch die Darstellung von Daten und Informationen in Dashboards zählt zur Kommunikation. Nicht zuletzt ist die graphische Darstellung von Infor-mationen zu Zeit, Ort und Person ein Teil dieses Surveillance-Schritts. Die Kommunikation von epidemiologischen Informationen stand zum Ende der Pandemie stark im Fokus und ist ein Bereich mit einem starken Entwicklungspotential. Nahezu weltweit gab es einen relevan-ten Anteil der Bevölkerung, die die Maßnahmen zur Bekämpfung der COVID-19 Pandemie abgelehnt haben und dadurch einen Einfluss auf den Verlauf der Pandemie hatten.
3.7	Schritt 7: Public Health Maßnahmen
Maßnahmen sind streng genommen kein Schritt der Surveillance, aber sie sind das Ziel auf das die Surveillance hinarbeitet. Public Health Maßnahmen sind alle absichtlichen Anstren-gungen von beauftragten Akteuren, die auf die Verhinderung der Weiterverbreitung und generell auf die Minimierung von Schaden durch Infektionskrankheiten gerichtet sind. Maß-nahmen sind häufig gesetzlich beschrieben zum Beispiel im Infektionsschutzgesetz. Maß-nahmen lassen sich in fallbezogene Maßnahmen und bevölkerungsbezogene Maßnahmen unterteilen. Fallbezogene Maßnahmen beinhalten zum Beispiel die Aufklärung einer be-troffenen Person über Übertragungswege oder auch Maßnahmen wie Quarantäne. Bevölke-rungsbezogene Maßnahmen sind Maßnahmen, die auf viele Menschen z.B. die Bevölkerung eines Bundeslandes einwirken. 



































## Events

Events are something that wants to be monitored. In infectious disease surveillance it is typically an infection. But i can also be other events as well: lab confirmation of a pathogen, free intensiv care beds, hospiatalisation because of a disease, vaccinations, death of person, a contact between to persons. One important but sometimes difficult distinction is differing between infection and disease. A lab confirmation usually shows an infection, which means that we know, that a person has a infection but is not necessarily sick, whereas a confirmation by a physician usually means that a person is sick. 

What event is monitored depends on the aim of the surveillance system. It is useful to be precise about the event that wants to be monitored. This helps in the communication and in the quality assessment. 
