---
subtitle: Generel presentations about infectious disease surveillance in english 
---

# Presentations (english) {.unnumbered}

## Attributes of surveillance systems

|Target|Description|
|---|---|
|Content|This presentation covers the attributes of a surveillance system. It covers underestimation, validty, timeliness and other attributes |
|Time|20 Minutes|
|Intended audience|Young professionals, Fellows of the European programme for intervention epidemiology| 
|Learning objectives|Be able to describe characteristics of a surveillance system|
```{=html}
<iframe class="slide-deck" src="presentation_attributes/"  width="960" height="500"></iframe>
```


## Evaluation of surveillance systems

|Target|Description|
|---|---|
|Content|This presentation gives an overview of how to evaluate a surveillance system. |
|Time|15 Minutes|
|Intended audience|Young professionals, Fellows of the European programme for intervention epidemiology| 
|Learning objectives|Learn the steps of an evaluation and that you need to adapt the evaluation to the trigger and the attributes you want to monitor|

```{=html}
<iframe class="slide-deck" src="presentation_evaluation/"  width="960" height="500"></iframe>
```

