---
title: "Step 1: Infection Event"
---

The infection-related events monitored in a surveillance system can be diverse. The term objects of a surveillance is sometimes used insted of event. The choice of the specific event has a decisive impact on the entire system. What event is monitored depends on the aim of the surveillance system. It is useful to be precise about the event that wants to be monitored. This helps in the communication and in the quality assessment. 

Surveillance systems are often named after the event that is monitored: Emergency room surveillance is one such example. Also the categorization of surveillance systems depends on the event being analyzed: For example, a system classified as “syndromic surveillance” is based on the monitoring of syndromes. 

A classic event that is monitored is the occurrence of an infectious disease in a person. However, there are many variations and other infection events that may be relevant: 

- an available ICU bed
- the colonization of a person by a pathogen
- a physician's ICD-10 classification of a patient
- the discovery of a newspaper article about a disease outbreak
- the subjective assessment of a public health department employee that something poses a threat to the population.

One important but sometimes difficult distinction is differing between infection and disease. A lab confirmation usually shows an infection, which means that we know, that a person has a infection but is not necessarily sick, whereas a confirmation by a physician usually means that a person is sick. 


