---
title: "Step 5: Analysis"
---

The analysis step consists of analyzing the data and subsequently drawing conclusions (assessment). In other words in the analysis steps the available data is transformed into information. In some cases, the analysis is straightforward; for example, when a case of Ebola is reported in a returning traveler, it is clear that this is an important event that necessitates action. In other cases, analysis is highly complex and requires a lot of experience and exchange between the evaluators: Is a relative increase in a variant of SARS-CoV-2 a reason for action? This analysis step converts data into information, following the first two parts of the "data–information–knowledge–wisdom" pyramid^[Rowley, J. (2007). The wisdom hierarchy: representations of the DIKW hierarchy. Journal of Information Science, 33(2), 163-180. [https://doi.org/10.1177/0165551506070706](https://doi.org/10.1177/0165551506070706)]. assessment is a subjective process and context-dependent. Knowledge of the limitations is particularly important for assessment. An increase in cases may seem like a clear event on paper but could be caused by intensified recording, making it less relevant and even a sign of relief, for example, if a comprehensive diagnostic of all hospital staff finds fewer cases than expected. The publication as open data means that the assessment is not only carried out by designated individuals but is open to everyone, enabling independent verification of this step in surveillance but also posing the risk of misinterpretation.


