---
title: "Evaluation"
---

## Steps for an evaluation
Step 1. Plan the evaluation (why evaluate, find attributes to evaluate, engage stakeholders, find team, evaluation protocol)
Step 2. Describe the system (objectives, events, case definitions, population under surveillance, geography, data flow, interventions)
Step 3. Perform the evaluation (depends on attributes)
Step 4. Develop an action plan (give interventions)


## Handbooks for evaluation
- ECDC 


## Describe a surveillance system
- Legal framework 
- Objectives of a surveillance system
- Public health actions for prevention and control
- Which information does the surveillance provide to inform these actions?
- Population under surveillance	
- Geographic coverage	
- Events under surveillance 
-	Type of surveillance	
- System’s indicators (e.g. Number of cases, Incidence, Percentage of people hospitalised)
- Notification of cases		
- Format of case notification	
- Format of reporting	
- Hierarchy levels in reporting	
- Who are the system’s participants/data providers
-	Who are the recipients/users of the system data 
