---
title: Objectives of surveillance (Stage 1)
subtitle: If you are clear about your objectives everything will be easier.
---

```{r, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
source("../graphs.R")
create_surveillance_plot(highlight = "Stage 1", output_type = "ggplot", language = "en")
```


The objectives of a surveillance system are the reasons why a surveillance systems is set into place. The overall objective of infectious disease surveillance is described nicely in the German infection protection act: 

> prevent communicable diseases in humans, detect infections at an early stage, and prevent their further spread^[Translated from the German infection protection act [https://www.gesetze-im-internet.de/ifsg/__1.html](https://www.gesetze-im-internet.de/ifsg/__1.html)]

The overarching objectiv can be decomposed into more conrete objectives that are based on the interventions that can be taken. These can be subdivided into primary objectives that have a direct effect on the spread of an infectious disease or secondary objectives that exert and indirect influence.

## Primary objectives
|Objective|Description|Example|
|---|---|
|Get information to initate case based action| All the interventions that are taken when there is a person with an infection | guidance/quarantine/isolation |
|Get information to initate population based action| All the interventions that are taken that affect a large part of the population|lockdown/school closings |
|Get information to initate individual action| interventions taken by the individual | mask, voluntary social distancing |
|Get information to initate action by medical professionals|The interventions that are taken by the medical system. A special form of the individual action | substitute antibiotic in response to antibiotic resistance |

## Secondary objectives
|Objective|Description|Example|
|---|---|
|Scientific advances|Advance the knowledge on infectious diseases|Research of change in vaccination uptake|
|Evaluation|Documents the impact of an intervention, or track progress towards specified goals|Evaluation of a safer-sex campaign|
|Resource allocation|Set priorities by the governmant or an institution and develope long term strategy|Set up laws the reduce legionella in drinking water|
|Fullfill obligation|Most nations have commited themselves to the International Health regulations. Thus they have to set up surveillance system| Doing a polio surveillance |

## Get information to initate case based action
Many public health interventions focus around the direct prevention of the spread from one person to another. This action is usually taken by a local public health agency. For this a surveillance systems needs to directly identify the single cases. So the objective of the surveillance system is to get all necessary information. 

## Get information to initate population based action
Some public health interventions focus on the population or a group. These interventions are sometimes described as non-pharmaceutical-interventions - although this sometimes also compromises case based interventions. This kind of intervention is often done via a regulation by a federal state or a national body. But it can also be taken by a local public health agency. This action requires usually only trends and not necessariliy case based information. So a surveillance system can have the objective to get the necessary information for this action 

## Get information to initate individual action
The information from surveillance systems can lead to people changing their behaviour. This compromises many different interventions, that are taken by the people themselves (if it is initatied by an agency it would be a population based intervention). These interventions can be ineffective or even counterproductive. So the surveillance can have the objective to elicit the information that is needed from the individuals to do effective and useful action.  

## Get information to initate action by medical professionals
Some findings of surveillance systems lead to a change in practice of medical professionals. A medical professional society could change the guidelines according to findings. This intervention is initiated by the medical people and not necessarily by the public health agencies. The objective of the surveillance could be based on eliciting the information needed.


## Scientific advances
Surveillance systems collect data that can also be used for public health research. Scientists can use the data to analyse specific public health problems. The system can give information about the nature of a pathogen and epidemiological characteristics of a public health problem. One example would be the change of variants that follow the introduction of a new vaccine.

## Evaluation
Public health interventions should be benefical for the population. The intervention can measure output, outcome and impact. Measuring the impact can be considered the most important part because it shows the benefits. This impact measurement can be done in with a surveillance system.

## Resource allocation
Governments need to decide about their priorities and the distribution of resources. These decisions can be taken upon the information from surveillance systems. 

## Fullfill obligation
The International health regulations require: _Each State Party shall develop, strengthen and maintain [...] the capacity to detect, assess, notify and report events_ Thus it can be an objective of a surveillance system to fullfill these obligations.


## Other concepts for objectives
There are other summaries for the objectives of a surveillance system that have a similar concepts. 

### World bank
 The world bank notes the objectives of an public health surveillance system as follows^[https://documents1.worldbank.org/curated/en/239131468160515361/pdf/536490BRI0ENGL10Box345621B01PUBLIC1.pdf]:  
_- recognize cases or clusters of cases to trigger interventions to prevent transmission or reduce morbidity and mortality (includes the special case in which surveillance at the national level is required to recognize multi-state clusters);
- identify new health problems and emerging diseases;
- assess public health impact of health events or determine and measure trends;
- measure causal factors in disease (e.g., risk factors) to initiate actions to prevent the onset of disease;
- demonstrate the need for intervention programs and resources, and allocate resources during health planning;
- monitor effectiveness and evaluate the impact of prevention and control measures, intervention strategies, and health policy changes;
- identify high-risk population groups or geographic areas to target interventions and guide analytic studies;
- provide data for research, and develop hypotheses that lead to analytic studies about risk factors for disease causation, propagation or progression;
- measure progress toward Millennium Development Goals, or other project or program goals, including PRSP (Poverty Reduction Strategy Paper) targets._


### EU/EEA surveillance
The EU/EEA surveillance ^[https://www.ecdc.europa.eu/sites/default/files/documents/long-term-surveillance-framework-2021-2027.pdf] focuses on the need for the supranational body
- Detect and monitor any multinational infectious disease outbreaks with respect to source, time, population, and place in order to provide a rationale for public health action;
- Monitor trends in infectious diseases over time and across Member States to assess the present situation, respond to rises above warning thresholds and facilitate appropriate evidence-based action;
- Contribute to the evaluation and monitoring of prevention and control programmes targeted at infectious diseases in order to provide the evidence for recommendations to strengthen and improve these programmes at the national and European level;
- Identify population groups at risk and in need of targeted prevention measures;
- Contribute to the awareness of and the assessment of the burden of infectious diseases on the population using such data as disease prevalence, complications, hospitalisation, and mortality; and
- Generate hypotheses on (new) sources, modes of transmission and groups most at risk and identify needs for research and pilot projects

## Objectives in practice
Although objectives play a decisive role in theory they are not as relevant in practice. Large surveillance systems tend to develope a life on its own and the focus on the objectives gets lost over time. New changes are introduced based on new needs but old parts stay in place although they might have losts their importance.  
