---
title: "Communication (Stage 7)"
subtitle: Communication in a complex world is difficult
---


```{r, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
source("../graphs.R")
create_surveillance_plot(highlight = "Stage 7", output_type = "ggplot", language = "en")
```


Communication is the dissemination of the obtained information in words, writing, and images. Communication consists of traditional elements such as press releases and press conferences or the preparation of reports. Communication now also includes social media and fact-checking. The presentation of data and information in dashboards also counts as communication.

## Graphical
the graphical representation of information is often done in terms of time, place, and person 




The communication of epidemiological information was a major focus towards the end of the pandemic and is an area with strong development potential. Almost worldwide, a significant portion of the population rejected the measures to combat the COVID-19 pandemic, thereby influencing the course of the pandemic.

