---
title: "Infection Event (Stage 2)"
subtitle: Choosing the right event is crucial and depends on the objectives
---

```{r}
source("../graphs.R")
create_surveillance_plot(highlight = "Stage 2")
```


Surveillance systems monitor a wide range of infection-related events. Understanding the event is essential for understanding a surveillance system.The choice of events to monitor in a surveillance system is a critical decision that shapes the system's in many ways. The choice depends on the Objective of the surveillance system. 

- If a case-based intervention is intended the event that is monitored should be able to provide contact information of a case
- If only goup-based intervention is inteded only a trend is needed which can be acquired by simpler systems
- When the objective of a surveillance system is to monitor hospital capacity for resource allocation decisions, the events tracked should focus on specific indicators of hospital capacity and utilization like bed occupancy of staff coverage.

## Naming and Categorization
Surveillance systems are often named after the events they monitor. For example:

- Emergency department surveillance (Emergency department visits)
- Syndromic surveillance (based on monitoring syndromes)
- Lab-based surveillance system (Reports by labs)
- Meidasurveillance (Screening of media articles)

## Typical events in infectious disease surveillance  
- The occurence of an infectious disease
- The occurence of an infection (infected person who is not necessarily diseased)
- An available ICU bed
- Self reports by people that they fell sick
- The colonization of a person by a pathogen
- A physician's ICD-10 classification of a patient
- The discovery of a newspaper article about a disease outbreak
- The subjective assessment of a public health department employee that something poses a threat to the population.
- A social media signal detected by a software  


