---
title: Objectives of surveillance
subtitle: Why do we need surveillance?
---

|Objective|Description|
|---|---|
|Action for cases| guidance/quarantine/isolation |
|Action for the population| lockdown/school closings |
|Action from the medical professionals| substitute antibiotic in response to antibiotic resistance |
|Action from the community| mask, voluntary social distancing |
|Detect and alert|Serves as an early warning system for impending public health emergencies|
|Describe|Monitors and clarify the epidemiology of health problems|
|Evaluate|Documents the impact of an intervention, or track progress towards specified goals|
|Inform|Allows priorities to be set and to inform public health policy and strategies|


## Example: Objectives of EU/EEA surveillance
- Detect and monitor any multinational infectious disease outbreaks with respect to source, time, population, and place in order to provide a rationale for public health action;
- Monitor trends in infectious diseases over time and across Member States to assess the present situation, respond to rises above warning thresholds and facilitate appropriate evidence-based action;
- Contribute to the evaluation and monitoring of prevention and control programmes targeted at infectious diseases in order to provide the evidence for recommendations to strengthen and improve these programmes at the national and European level;
- Identify population groups at risk and in need of targeted prevention measures;
- Contribute to the awareness of and the assessment of the burden of infectious diseases on the population using such data as disease prevalence, complications, hospitalisation, and mortality; and
- Generate hypotheses on (new) sources, modes of transmission and groups most at risk and identify needs for research and pilot projects

## Action for cases
Many public health interventions focus around the identification of cases and their surroundings. This action is usually taken by a local public health agency. For this objective a surveillance systems needs to directly identify cases together with the possibility to contact the case.

Typical interventions taken are:
  - guidance: The local public gives the case or his contact persons guidance on what to do and how to behave
 - mandate: The local public health official could order a case or a contact person to do something. This could be quarantine for example
 - information: the local public health agency informs everybody who needs to know about this public health event
 
## Action for the population
Some public health interventions focus a specific group of people. These interventions are sometimes described as non-pharmaceutical-interventions - although this sometimes also compromises case based interventions. This kind of intervention is often done via a regulation by a federal state or a national body. But it can also be taken by a local public health agency, especially if the public health problem is local. This action requires usually only trends and not necessariliy case based information. 

Typical interventions are:
- Boiling water before drinking
- Requiring to wear masks
- Closing schools
- Giving advice

## Action taken from medical professionals
Some findings of surveillance systems lead to a change in practice of medical professionals. A medical professional society could change the guidelines according to findings. This intervention is initiated by the medical people and not necessarily by the public health agencies

Typical interventions are:
- change in calculated antibitotic therapy (so before information about resistance of the specific pathogen is available) according to a higher resistancy in an area
- change in immunization strategies

## Action taken from the community
The information from surveillance systems can lead to people changing their behaviour. This compromises many different interventions, that are taken by the people themselves (if it is initatied by an agency it would be a group-based intervention). These interventions can be ineffective or even counterproductive. 

Typical interventions are:
- Wearing masks
- Washing handy frequently
- Not using public transport
- Avoiding specific groups

## Detect and alert
Surveillance systems serve to detect impeding public health problems and then to alert the ones who need to be alerted. Systems that are build to do this are called early-warning system. The systems can be very broad in nature and usually rely on detecting a trend. 

## Describe
Surveillance systems collect data that can also be used for public health research. Scientists can use the data to analyse specific public health problems. The system can give information about the nature of a pathogen and epidemiological characteristics of a public health problem. One example would be the change of variants that follow the introduction of a new vaccine.

## Evaluation
Public health interventions should be benefical for the population. The intervention can measure output, outcome and impact. Measuring the impact can be considered the most important part because it shows the benefits. This impact measurement can be done in with a surveillance system.

## Inform
Governments need to decide about their priorities and the distribution of resources. These decisions can be taken upon the information from surveillance systems. 
