---
title: Other forms of surveillance
subtitle: What is the larger picture of surveillance?
---

Nearly all complex biological and technical systems have mechanisms to monitor and control the system's condition. Many social systems also regularly analyze their current state. There are various terms for these status assessments: A scientific study is one form of status assessment, as is the police surveillance of a group or the evaluation of a project in the corporate sector. Surveillance is also a form of status assessment.

## Neighbourhood surveillance
Neighbourhood surveillance is the oldest form of surveillance. In its broadest sense it es people watching other people. Small Communities such as villages usually have a strong neighbourhood surveillance. Neighbors see and know everything what other neigbohrs are doing. This can be framed positively as in the saying: "it takes a village to raise a child" or negatively when people blaspheme other people. 

With the widespread availability of cameras and the possibility to communicate directly this form of surveillance has gained a large momentum. The largely unsuccesfull Google glass project could have been an even larger driver of participatory surveillance. Now Surveillance becomes a tool that does not lie in the hands of a strong actor such as a state or less strong actors such as companies but in the hands of the individuals. This gives infectious disease specialists the opportunity to gather information from thos eindividuals as it is done in epidemic intelligence. 

This form of surveillance is sometimes also called participatory surveillance - if you want to emphasize the empowerment of the people. One rather negative example of a participatory surveillance is vividly depicted in the book and film the circle. Sometimes this form of surveillance is called bottom-up-surveillance to emphasize the opposition to top-down-surveillance.    

## Rhizomatic surveillance
Rhizomatic surveillance is a term coined by Haggerty and Ericson^[Haggerty KD, Ericson RV. The surveillant assemblage. Br J Sociol. 2000 Dec;51(4):605-22. doi: 10.1080/00071310020015280. [https://pubmed.ncbi.nlm.nih.gov/11140886/](https://pubmed.ncbi.nlm.nih.gov/11140886/)]. The term comes from rhizom - the large underground network from Fungi. This form of surveillance shows similar characteristics of the rhizom: is is being not directly visible (being "underground")), it is horizontal in contrast to the top-down surveillance (like the rhizom that does not follow the typical direction of plants growing upwards to the sun)) and the surveillance is a group of different actors instead of one single responsible body. 
The surveillance done by the big tech companies is a form a rhizomatic surveillance. Collecting millons of datapoints that are left behind by users in the internet can give valuable inside that can be turned into profit. The cambridge analytica scandal is an example of such a surveillance system. State actors are of course also capable of doing rhizomatic survaillance as could bee seen in the documents leaked to PRISM.

## Top-down-surveillance
The top-down-surveillance is the surveillance which we usually think of first when we hear the word surveillance. There is an agent usually a dominent one like the state who watches was its constituents do. This can take the form of an Panopticon, where one person can watch many different person and after which some prisons have been modeled. This form of surveillance often aims to achieve a specific behavior among those being monitored. Epidemiological surveillance belongs to this level of surveillance. 

## Learn more
You can read more about different types of surveillance in this article by Tieman et al. ^[ Timan, Tjerk and Galič, Maša and Koops, Bert-Jaap, Surveillance Theory and Its Implications for Law (December 1, 2017) [https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3098182](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3098182)]



 
